project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning"
  navbar:
    left:
      - href: index.qmd
        text: Modelacion de balance de masa glaciar
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    fig-align: center